name: my_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Eesti
      fonts:
        - asset: assets/fonts/GT-Eesti-Bold.otf
        - asset: assets/fonts/GT-Eesti-Light.otf
        - asset: assets/fonts/GT-Eesti-Regular.otf
        - asset: assets/fonts/GT-Eesti-Thin.otf
 
  assets:
    - assets/images/blabla_home.png
